### ISSUE TITLE
Initialisation

### ISSUE THREAD

**Issue by jbcaillau** [mctao-inria/sail-therm#3]
![IMG_3253](https://github.com/mctao-inria/sail-therm/assets/62183989/d0e65b39-e1e6-4298-8286-197574579bfd)

@alesiagr 
- initialisation vectorielle (pour état et / ou contrôle), pas matricielle mais *vecteur de vecteur*, je pense
- oui, on peut donner (pour état et / ou contrôle) soit des fonctions du temps, soit des vecteurs (version discrétisée)
- fonction du temps donc $u(t)$, en effet, pas $u(x)$ (mais si tu connais un  `u(x)` et un `x_init`, il suffit de passer `u_init = u.(x_init)`)
- le [tuto](https://control-toolbox.org/docs/ctdirect/stable/tutorial.html#Initial-guess-options) pour initialisations

**Comment by alesiagr** [comment]
@jbcaillau je viens de faire un push parce que j'arrive pas à le faire fonctionner. J'obtiens des résultats un peu étranges sans initial guess, j'essaie de voir comment les visualiser en regardant https://github.com/control-toolbox/CTBase.jl/blob/b73f56d6447e1967bf56c59f49dc8bcdb09dd71c/src/plot.jl

**Comment by jbcaillau** [comment]
OK : je pulle et regarde

**Comment by jbcaillau** [comment]
@alesiagr dans la branche `develop` : 
- quelques corrections de [style](xxxxx) 🙂 (j'espère n'avoir rien cassé)
- j'ai vu après coup que tu avais extrait plusieurs fonctions auxiliaires (et fait des `include`), je vais mettre à jour
- surtout : l'opti ne converge pas (erreurs numériques...) À suivre

**Comment by alesiagr** [comment]
J'ai vu, merci! Je pense avoir trouvé le pb de git, je viens de faire le request pour que tu m'autorises s'il te plaît :)

**Comment by alesiagr** [comment]
J'ai réussi à faire marcher GitHub après 4 jours! Il fallait faire un personal access token apparemment.... 🥲 Enfin ça marche... Je regarde le code pour comprendre pourquoi il veut pas converger. 

C'est possible que j'ai écrasé un de tes push @jbcaillau , désolée pour ça. Mais c'est parce que jusqu'à présent je ne pouvais faire commit qu'en uploadant le fichier dans le browser.

**Comment by alesiagr** [comment]
Salut @jbcaillau, il y a qqch que je n'arrive pas à comprendre en Julia, c'est la manière de créer des vecteurs/ matrices. Ma fonction F0 ne fonctionne pas quand j'essaie de la propager avec ODEProblem (voir fichier test.jl), donc j'ai dû la re-écrire sous la forme non-matricielle, ligne par ligne, comme on le faisait avant. Si je fais ça avec OptimalControl.jl, ça fonctionne pas non plus. J'ai aussi l'erreur de ForwardDiff.jl qui apparait lorsque je réécris la fonction ligne par ligne, mais sinon le code ne converge pas tout court...

**Comment by jbcaillau** [comment]
coucou @alesiagr dispo demain 17:00 pour un point ?

**Comment by alesiagr** [comment]
hello @jbcaillau , 18h fonctionne pour toi?

**Comment by jbcaillau** [comment]
> hello @jbcaillau , 18h fonctionne pour toi?
yes: [webex](https://inria.webex.com/meet/jean-baptiste.caillau)
